### ISSUE TITLE
Add to Sugar instead of a separate package

### ISSUE THREAD

**Issue by rhl-bthr** [dnarvaez/gwebsockets#1]
@quozl, can we add this to [sugar](https://github.com/sugarlabs/sugar) instead of keeping it as a separate package ?

**Comment by quozl** [comment]
I'll fork to sugarlabs so we can remember we use it, but as @dnarvaez vanished, I'm not sure we can do much about this original repository.

In another fork, https://github.com/curiousguy13/gwebsockets contains a port to Python 3.

**Comment by rhl-bthr** [comment]
> In another fork, https://github.com/curiousguy13/gwebsockets contains a port to Python 3.

yes, I reviewed that. My plan is to embed `dnarvaez/master` in `sugar` now itself, and apply the patch to port later. In your opinion, will there be an advantage in keeping it as a separate package ?

**Comment by quozl** [comment]
I'm not quite sure what you mean.  To me, a _package_ is usually a `.deb` or `.rpm` file.  But perhaps you mean Python _module_?  gwebsockets is a package now, on Debian and Ubuntu, and there may be software depending on it, so I suggest porting it to Python 3, make a release in absence of @dnarvaez, and mention the new release to Fedora and Debian team.

**Comment by rhl-bthr** [comment]
Sure, will do that
